import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snake Game By Topu",
  description:
    "Full Stack Snake Game by Topu Roy (Full Stack React Web Developer). Generated by create next app. I worked on both the front and back ends, using Next.js for speed, TypeScript for typing, and Tailwind CSS for styling. On the back end, I used Prisma for databases, MongoDB for NoSQL, Zustand for state management, and Zod for schema validation. This project helped me improve my skills, solve problems, and learn new things. It shows my dedication to learning and pushing boundaries in the world of development.",
  authors: {
    name: 'Topu Roy',
    url: 'https://github.com/Topu-Roy/'

  },
  keywords: "react snake game, nextjs snake game, topu roy, topu, web developer topu roy"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" bg-gray-800">
      <head>
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={inter.className}>
        <main>
          <NavBar />
          {children}
          <Analytics />
        </main>
      </body>
    </html>
  );
}
